---
amqp:
  de:
    name: de
    auto_delete: false
    durable: true
    type: topic

    ## Connection parameters
    scheme: amqp
    user: "{{ amqp_de_user }}"
    password: "{{ amqp_de_password }}"
    host: "{{ groups['amqp-brokers'][0] }}"
    port: "{{ amqp_de_port }}"
    vhost: "/{{ environment_name }}/de"
    mgmt_port: "{{ amqp_de_management_port }}"
  notification:
    routing: notification.*

  irods:
    name: irods
    auto_delete: false
    durable: true
    type: topic

    ## Connection parameters
    scheme: amqp
    user: "{{ amqp_irods_user }}"
    password: "{{ amqp_irods_password }}"
    host: "{{ groups['irods-amqp-brokers'][0] if groups['irods-amqp-brokers']|count else ''}}"
    port: "{{ amqp_irods_port }}"
    vhost: "/{{ environment_name }}/data-store"
    mgmt_port: "{{ amqp_irods_management_port }}"

amqp_de_uri: "{{ amqp.de.scheme }}://{{ amqp.de.user }}:{{ amqp.de.password | urlencode }}@{{ amqp.de.host }}:{{ amqp.de.port }}/{{ amqp.de.vhost | urlencode }}"
amqp_irods_uri: "{{ amqp.irods.scheme }}://{{ amqp.irods.user }}:{{ amqp.irods.password | urlencode }}@{{ amqp.irods.host }}:{{ amqp.irods.port }}/{{ amqp.irods.vhost | urlencode }}"
