---
de_base: "{{ app_base }}/de"
de:
  host: "ui"
  base: "{{ de_base }}"
  app_base: "{{ app_base }}"
  context_menu_enabled: true
  description: "the CyVerse Discovery Environment"
  empty_url: "empty"
  app_name: "de"
  rpc_name: "discoveryenvironment"
  notification_poll: "15"
  maintenance_file: "de-maintenance"
  local_ip_ranges:
  http_server:
    ssl:
      server_name: "{{ nginx_ssl.server_name }}"
      cert: "{{ nginx_ssl.cert }}"
      cert_key: "{{ nginx_ssl.cert_key }}"
      cert_combined: "{{ nginx_ssl.cert_combined }}"
      insecure_redirects:
        - server_name: "{{ nginx_ssl.server_name }}"
          return: "https://$host$request_uri"
      redirects:
